using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SampleWebApi.Models
{
    //This is our Entity class that will be used to share among our clients. The Entity class auto generated by the EF is not recommended to be shared to the clients. Instead its good to create our Entity classes and do the required Conversions. 
    public class Employee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal Salary { get; set; }

        public EmpTable Convert()
        {
            return new EmpTable
            {
                EmpID = this.ID,
                EmpAddress = Address,
                EmpName = Name,
                EmpSalary = Salary
            };
        }

        public void Convert(EmpTable record)
        {
            ID = record.EmpID;
            Name = record.EmpName;
            Address = record.EmpAddress;
            Salary = record.EmpSalary;
        }
    }
}