using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;
using WcfClient.myWcfReferences;//Similar to Web Services....

//Apps will add Service Reference for WCF Components to be used in their Application. The Service Reference creates a Proxy class whose object is used to call the methods of the WCF Component. 

namespace WcfClient
{
    class Program
    {
        static void Main(string[] args)
        {
            //The proxy class that is generated by the WCF will be the name of the interface suffixed with Client.
            //insertRegistration();
            readAllCustomers();
            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }//Press f5 to execute the Application....

        private static void readAllCustomers()
        {
            var proxy = new SportServiceClient();
            var data = proxy.GetAllCustomers();
            foreach(var cst in data)
                Console.WriteLine(cst.Name  + " has paid " + cst.Fees);
        }

        private static void insertRegistration()
        {
            try
            {
                SportServiceClient proxy = new SportServiceClient();
                proxy.RegisterUser(new Customer
                {
                    Name = "Rahul",
                    ContactNo = 23424555
                });//U should also add the ID if the Db does not have identity...
            }
            catch (FaultException fx)
            {
                Console.WriteLine(fx.Message);
            }
            catch (CommunicationException ex)//WCF related Exceptions
            {
                Console.WriteLine(ex.Message);
            }
            catch (Exception genEx)
            {
                Console.WriteLine(genEx.Message);
            }
        }
    }
}
